- name: Stop and remove Docker container if any
  docker_container:
    name: web_app_container
    state: absent
  when: web_app_full_wipe
  tags:
    - wipe

- name: Remove Docker Compose file
  file:
    path: /home/{{ ansible_user }}/docker-compose.yml
    state: absent
  when: web_app_full_wipe
  tags:
    - wipe